DROP TABLE IF EXISTS users;
CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS members;
CREATE TABLE members (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    position VARCHAR(40) NOT NULL,
    body TEXT NOT NULL,
    picture VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS events;
CREATE TABLE events (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(40) NOT NULL,
    body TEXT NOT NULL,
    picture VARCHAR(100) NOT NULL,
    post_date VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS sponsors;
CREATE TABLE sponsors (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    body TEXT NOT NULL,
    picture VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS socials;
CREATE TABLE socials (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    href VARCHAR(100) NOT NULL,
    platform VARCHAR(30) NOT NULL
);
